"""empty message

Revision ID: 04b74e78a0d7
Revises: ec4e6be8241d
Create Date: 2020-12-09 00:21:39.403534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04b74e78a0d7'
down_revision = 'ec4e6be8241d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'listing_source', ['description'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'listing_source', type_='unique')
    # ### end Alembic commands ###
