"""empty message

Revision ID: 63fb83eacfc1
Revises: d1c407f30c9e
Create Date: 2020-12-09 17:52:34.511108

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63fb83eacfc1'
down_revision = 'd1c407f30c9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('description', table_name='listing_source')
    op.drop_table('listing_source')
    op.drop_index('ix_listing_listing_date', table_name='listing')
    op.drop_index('ix_listing_user_id', table_name='listing')
    op.drop_table('listing')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_first_name', table_name='user')
    op.drop_index('ix_user_last_name', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('first_name', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('`is_admin` in (0,1)', name='CONSTRAINT_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.create_index('ix_user_last_name', 'user', ['last_name'], unique=False)
    op.create_index('ix_user_first_name', 'user', ['first_name'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.create_table('listing',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('listing_date', sa.DATE(), nullable=True),
    sa.Column('source_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('description', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('address_1', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('address_2', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('post_code', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('outgoing', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('modified_date', mysql.DATETIME(), nullable=True),
    sa.CheckConstraint('`outgoing` in (0,1)', name='CONSTRAINT_1'),
    sa.ForeignKeyConstraint(['source_id'], ['listing_source.id'], name='listing_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='listing_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_listing_user_id', 'listing', ['user_id'], unique=False)
    op.create_index('ix_listing_listing_date', 'listing', ['listing_date'], unique=False)
    op.create_table('listing_source',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('description', 'listing_source', ['description'], unique=True)
    # ### end Alembic commands ###
