"""empty message

Revision ID: e6d8739e721b
Revises: 9b14cb7e955b
Create Date: 2020-12-04 20:58:10.507588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d8739e721b'
down_revision = '9b14cb7e955b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('email_address', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing', 'email_address')
    # ### end Alembic commands ###
