"""empty message

Revision ID: ec4e6be8241d
Revises: e6d8739e721b
Create Date: 2020-12-05 00:27:19.862918

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec4e6be8241d'
down_revision = 'e6d8739e721b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('listing', sa.Column('email', sa.String(length=40), nullable=True))
    op.add_column('listing', sa.Column('modified_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_listing_listing_date'), 'listing', ['listing_date'], unique=False)
    op.create_index(op.f('ix_listing_user_id'), 'listing', ['user_id'], unique=False)
    op.drop_column('listing', 'email_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('email_address', mysql.VARCHAR(length=40), nullable=True))
    op.drop_index(op.f('ix_listing_user_id'), table_name='listing')
    op.drop_index(op.f('ix_listing_listing_date'), table_name='listing')
    op.drop_column('listing', 'modified_date')
    op.drop_column('listing', 'email')
    op.drop_column('listing', 'created_date')
    # ### end Alembic commands ###
